### ISSUE TITLE
SPI Advice

### ISSUE THREAD

**Issue by notpike** [m5stack/M5Stack#242] opened 2021-02-13 18:07 UTC
Hi,

I'm looking for advice on how to implement a CC1101 radio module so it shares the same SPI bus as the LCD and SD on the M5Stack. I'm working with the M5Stack Core (Black) and I'm able to use the CC1101 via SPI when I don't use the M5Stack library isn't being loaded. However when I try to use both CC1101 and the M5Stack libs at the same time I believe there's an SPI conflict. Not sure how or where to look but I would like to know if you had any advice on where to have both coexist.

Thanks!
NotPike

**Comment by Tinyu-Zhao** [comment] 2024-07-23 04:06
Sorry for the late reply. I saw that the CC1101 has a CS chip select pin. In theory, if communication is not carried out through SPI at the same time, there should be no conflict. Because the problem is too old, I will close this issue. If you still need help, please open the issue again and provide us with your code.

<img width="910" alt="image" src="https://github.com/user-attachments/assets/7290163a-9dc5-4bae-9c98-6b21c6723c53">

**Closed by Tinyu-Zhao** 2024-07-23 04:06 UTC
