### ISSUE TITLE
can't compile on macos

### ISSUE THREAD

**Issue by Keoni80** [m5stack/M5Stack#164] opened 2019-05-17 21:11 UTC
trying to compile the basic example and always have the same error:

/Users/juan/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp: In member function 'void POWER::powerOFF()':
/Users/juan/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp:360:35: error: 'ESP_SLEEP_WAKEUP_ALL' was not declared in this scope
   esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_ALL);

                                   ^
/Users/juan/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp:361:28: error: 'gpio_deep_sleep_hold_dis' was not declared in this scope
   gpio_deep_sleep_hold_dis();

                            ^
Se encontraron múltiples librerías para "SD.h"
Usado: /Users/juan/Documents/Arduino/hardware/espressif/esp32/libraries/SD
 No usado: /Applications/Arduino.app/Contents/Java/libraries/SD
exit status 1
Error compilando para la tarjeta M5Stack-Core-ESP32.

it works fine on windows :S

**Comment by lovyan03** [comment] 2019-05-17 23:10
Probably, need update ArduinoESP32 (v1.0.2)

**Comment by Keoni80** [comment] 2019-05-20 16:21
how do i do that?

**Comment by Keoni80** [comment] 2019-05-20 16:36
done, i deleted the main folder, and then reinstall , thanks

**Comment by brentru** [comment] 2019-05-20 20:33
Having this issue as well:

```
/Users/brentrubell/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp: In member function 'void POWER::powerOFF()':
/Users/brentrubell/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp:360:35: error: 'ESP_SLEEP_WAKEUP_ALL' was not declared in this scope
   esp_sleep_disable_wakeup_source(ESP_SLEEP_WAKEUP_ALL);

                                   ^
/Users/brentrubell/Documents/Arduino/libraries/M5Stack/src/utility/Power.cpp:361:28: error: 'gpio_deep_sleep_hold_dis' was not declared in this scope
   gpio_deep_sleep_hold_dis();

                            ^
Multiple libraries were found for "WiFi.h"
 Used: /Users/brentrubell/Documents/Arduino/hardware/espressif/esp32/libraries/WiFi
 Not used: /Users/brentrubell/Documents/Arduino/libraries/WiFiNINA
 Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi
Multiple libraries were found for "SD.h"
 Used: /Users/brentrubell/Documents/Arduino/hardware/espressif/esp32/libraries/SD
 Not used: /Users/brentrubell/Documents/Arduino/libraries/SD
 Not used: /Applications/Arduino.app/Contents/Java/libraries/SD
```

**Comment by lovyan03** [comment] 2019-05-21 00:39
Maybe, that is not the latest (arduino-esp32 v1.0.2 release).

![image](https://user-images.githubusercontent.com/42724151/58060339-f3b72180-7bab-11e9-9fd6-0cea884bb1ac.png)

**Comment by brentru** [comment] 2019-05-22 23:40
@lovyan03 Looks like it didn't release properly from them, works OK now. Feel free to close!

**Comment by rodlenz** [comment] 2019-05-24 01:27
Dear @Keoni80 I`m facing the exactly same issue, do you mind to explain in more details what exqactly you did to solve this problem? Tks in advance for the additional help.

**Comment by Keoni80** [comment] 2019-05-24 01:44
@rodlenz i deleted the ESP32 folder, and downloaded again with terminal, then it works with arduino IDE, but still doesn't work with PlatformIO

**Comment by rayozzie** [comment] 2019-06-19 13:14
macOS Mojave, Arduino 1.8.9, esp32 1.0.2, Examples/M5Stack/Basics/Display, error compiling for board M5Stack-Core-ESP32:

`Arduino: 1.8.9 (Mac OS X), Board: "M5Stack-Core-ESP32, QIO, 80MHz, Default, 921600, None"

Build options changed, rebuilding all
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setKey(char*, char*, char*)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:109:41: warning: large integer implicitly truncated to unsigned type [-Woverflow]
         loraDebugPrint(DEFAULT_DEBUGTIME);
                                         ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:120:41: warning: large integer implicitly truncated to unsigned type [-Woverflow]
         loraDebugPrint(DEFAULT_DEBUGTIME);
                                         ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:131:41: warning: large integer implicitly truncated to unsigned type [-Woverflow]
         loraDebugPrint(DEFAULT_DEBUGTIME);
                                         ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'bool LoRaWanClass::setDataRate(_data_rate_t, _physical_type_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:144:38: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
       debugPrint("Unknown datarate\n");
                                      ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:159:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:167:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:140:17: warning: unused variable 'str' [-Wunused-variable]
     const char *str;
                 ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setPower(short int)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:180:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setPort(unsigned char)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:193:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setAdaptiveDataRate(bool)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:203:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::getChannel()':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:212:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setChannel(unsigned char, float)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:230:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setChannel(unsigned char, float, _data_rate_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:245:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setChannel(unsigned char, float, _data_rate_t, _data_rate_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:260:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setUnconfirmedMessageRepeatTime(unsigned char)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:562:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setConfirmedMessageRetryTime(unsigned char)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:578:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::getReceiveWindowFirst()':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:586:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setReceiveWindowFirst(bool)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:597:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setReceiveWindowFirst(unsigned char, float)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:615:41: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME * 4);        // this can have a lot of data to dump
                                         ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setReceiveWindowSecond(float, _data_rate_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:628:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setReceiveWindowSecond(float, _spreading_factor_t, _band_width_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:641:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setReceiveWindowDelay(_window_delay_t, short unsigned int)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:657:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setClassType(_class_type_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:667:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'bool LoRaWanClass::setOTAAJoin(_otaa_join_cmd_t, unsigned char)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:708:11: warning: unused variable 'ptr' [-Wunused-variable]
     char *ptr;
           ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceLowPower()':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:770:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceReset()':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:782:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'void LoRaWanClass::setDeviceDefault()':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:794:37: warning: large integer implicitly truncated to unsigned type [-Woverflow]
     loraDebugPrint(DEFAULT_DEBUGTIME);
                                     ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'bool LoRaWanClass::setDataRate(_data_rate_t, _physical_type_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:170:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'short int LoRaWanClass::receivePacket(char*, short int, short int*)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:490:43: error: 'tmp' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 result = result * 16 + tmp;
                                           ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:448:43: error: 'tmp' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 result = result * 16 + tmp;
                                           ^
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp: In member function 'short int LoRaWanClass::receivePacketP2PMode(unsigned char*, short int, short int*, unsigned char)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/LoRaWan.cpp:875:43: error: 'tmp' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 result = result * 16 + tmp;
                                           ^
cc1plus: some warnings being treated as errors
Multiple libraries were found for "SD.h"
 Used: /Users/rozzie/Library/Arduino15/packages/esp32/hardware/esp32/1.0.2/libraries/SD
 Not used: /Users/rozzie/Documents/Arduino/libraries/SD
 Not used: /Applications/Arduino.app/Contents/Java/libraries/SD
exit status 1
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/M5Display.cpp: In member function 'void M5Display::drawBmpFile(fs::FS&, const char*, uint16_t, uint16_t)':
/Users/rozzie/Documents/Arduino/libraries/M5Stack-master/src/M5Display.cpp:127:23: warning: unused variable 'col' [-Wunused-variable]
   uint16_t w, h, row, col;
                       ^
Error compiling for board M5Stack-Core-ESP32.

`

**Comment by Zontex** [comment] 2020-11-11 06:53
Seems the problem has been solved, closing the issue.

**Closed by Zontex** 2020-11-11 06:53 UTC
