### ISSUE TITLE
drawCentreString and drawRightString causes Exception

### ISSUE THREAD

**Issue by Kabron287** [m5stack/M5Stack#45] opened 2018-03-02 10:26 UTC
Any use of these function causes Exception.
I do not want to find the bug in Display.cpp, so, as a temporary solution I'm using
`#define drawCentreString	drawString

#define drawRightString		drawString
`

**Comment by Zontex** [comment] 2020-11-12 03:23
could you please provide your entire code and which M5Stack product are you using? I'm closing it for now as the issue is too old, if it's still relevant feel free to open it.

**Closed by Zontex** 2020-11-12 03:23 UTC

**Comment by Kabron287** [comment] 2020-11-12 05:32
Yes, close it
